swagger: "2.0"
info:
  version: 1.0.0
  title: Movie API
  description: REST API for Movie APP
basePath: /api
tags:
  - name: movies
    description: Simple movie endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  movieBody:
    type: object
    title: movie
    required:
      - title
    properties:
      title:
        type: string
        description: The movie name

paths:
  /movies:
    get:
      tags:
        - Movies
      description: Fetch all movies
      responses:
        200:
          description: Returns all movies
    post:
      tags:
        - movies
      description: Create a new movie
      parameters:
        - name: movie
          in: body
          description: number of items to skip
          required: true
          schema: 
            $ref: "#/definitions/movieBody"
      responses:
        200:
          description: Returns all movies

  /movies/{id}:
    get:
      tags:
        - movies
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
      responses:
        200:
          description: Return the movie with the specified id
        404:
          description: movie not 

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification